version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli cfn-lint

  pre_build:
    commands:
      - cfn-lint lambda2/template.yaml
      - sam validate -t lambda2/template.yaml

  build:
    commands:
      - sam build --use-container --template-file lambda2/template.yaml
      - sam package
        --template-file .aws-sam/build/template.yaml
        --s3-bucket $S3_BUCKET
        --s3-prefix lambda2/$CODEBUILD_RESOLVED_SOURCE_VERSION
        --output-template-file packaged.yaml
        --region $AWS_REGION
      

artifacts:
  files:
    - packaged.yaml

cache:
  paths:
    - '/root/.cache/pip/**/*'
