# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - python --version
#       - pip install --upgrade pip
#       - pip install aws-sam-cli cfn-lint
#       - echo "ENVIRONMENT=$ENVIRONMENT"
#       - echo "AWS_REGION=$AWS_REGION"
#       - echo "S3_BUCKET=$S3_BUCKET"

#   pre_build:
#     commands:
#       # Hash layer requirements
#       - LAYER_HASH=$(md5sum lambda1/layers/lib/requirements.txt | awk '{print $1}' | cut -c1-8)
#       - echo "LAYER_HASH=$LAYER_HASH"
#       - echo "LAYER_HASH=$LAYER_HASH" >> /tmp/build.env

#       # Hash role template
#       - ROLE_HASH=$(md5sum lambda1/template-role.yaml | awk '{print $1}' | cut -c1-8)
#       - echo "ROLE_HASH=$ROLE_HASH"
#       - echo "ROLE_HASH=$ROLE_HASH" >> /tmp/build.env

#       # Decide if role deploy needed (based on existing role tag)
#       - |
#         ROLE_NAME="lambda1-execution-role-${ENVIRONMENT}"
#         EXISTING_ROLE_HASH="$(aws iam get-role \
#           --role-name "$ROLE_NAME" \
#           --query "Role.Tags[?Key=='RoleHash'].Value | [0]" \
#           --output text 2>/dev/null || echo "none")"

#         echo "EXISTING_ROLE_HASH=$EXISTING_ROLE_HASH"
#         if [ "$EXISTING_ROLE_HASH" = "$ROLE_HASH" ]; then
#           echo "SKIP_ROLE_DEPLOY=true" >> /tmp/build.env
#         else
#           echo "SKIP_ROLE_DEPLOY=false" >> /tmp/build.env
#         fi

#       # Decide if layer deploy needed (compare stack parameter)
#       - |
#         LAYER_STACK_NAME="lambda1-layer-${ENVIRONMENT}"
#         STACK_EXISTS="$(aws cloudformation describe-stacks \
#           --stack-name "$LAYER_STACK_NAME" \
#           --region "$AWS_REGION" \
#           --query "Stacks[0].StackId" \
#           --output text 2>/dev/null || echo "none")"

#         if [ "$STACK_EXISTS" != "none" ]; then
#           EXISTING_LAYER_HASH="$(aws cloudformation describe-stacks \
#             --stack-name "$LAYER_STACK_NAME" \
#             --region "$AWS_REGION" \
#             --query "Stacks[0].Parameters[?ParameterKey=='LayerContentHash'].ParameterValue | [0]" \
#             --output text 2>/dev/null || echo "none")"
#           echo "EXISTING_LAYER_HASH=$EXISTING_LAYER_HASH"
#           if [ "$EXISTING_LAYER_HASH" = "$LAYER_HASH" ]; then
#             echo "SKIP_LAYER_DEPLOY=true" >> /tmp/build.env
#           else
#             echo "SKIP_LAYER_DEPLOY=false" >> /tmp/build.env
#           fi
#         else
#           echo "SKIP_LAYER_DEPLOY=false" >> /tmp/build.env
#         fi

#       # Bundle shared into lambda1/
#       - rm -rf lambda1/shared
#       - mkdir -p lambda1/shared
#       - rsync -a --delete shared/ lambda1/shared/

#       # Validate templates
#       # - cfn-lint lambda1/template.yaml lambda1/template-role.yaml lambda1/template-layer.yaml
#       - sam validate -t lambda1/template.yaml
#       - sam validate -t lambda1/template-role.yaml
#       - sam validate -t lambda1/template-layer.yaml

#   build:
#     commands:
#       - . /tmp/build.env

#       # Deploy role stack if needed
#       - |
#         if [ "$SKIP_ROLE_DEPLOY" != "true" ]; then
#           echo "=== Deploying ROLE stack ==="
#           sam build --use-container --template-file lambda1/template-role.yaml
#           sam package \
#             --template-file .aws-sam/build/template.yaml \
#             --s3-bucket "$S3_BUCKET" \
#             --s3-prefix "lambda1/role/$CODEBUILD_RESOLVED_SOURCE_VERSION" \
#             --output-template-file packaged-role.yaml \
#             --region "$AWS_REGION"

#           sam deploy \
#             --template-file packaged-role.yaml \
#             --stack-name "lambda1-role-${ENVIRONMENT}" \
#             --parameter-overrides "Environment=$ENVIRONMENT" "RoleHash=$ROLE_HASH" \
#             --capabilities CAPABILITY_NAMED_IAM \
#             --region "$AWS_REGION" \
#             --no-fail-on-empty-changeset
#         else
#           echo "Skipping role deploy (no changes) ${ROLE_HASH}"
#         fi

#       # Ensure role export exists (retry loop to avoid eventual consistency)
#       - |
#         echo "=== Waiting for ROLE export to appear ==="
#         for i in 1 2 3 4 5 6; do
#           ROLE_EXPORT="$(aws cloudformation list-exports \
#             --region "$AWS_REGION" \
#             --query "Exports[?Name=='lambda1-execution-role-arn-${ENVIRONMENT}'].Name | [0]" \
#             --output text 2>/dev/null || echo "none")"
#           if [ "$ROLE_EXPORT" != "none" ] && [ "$ROLE_EXPORT" != "None" ]; then
#             echo "Role export found."
#             break
#           fi
#           echo "Role export not found yet (attempt $i) - sleeping 5s"
#           sleep 5
#         done
#         if [ "$ROLE_EXPORT" = "none" ] || [ "$ROLE_EXPORT" = "None" ]; then
#           echo "ERROR: Role export still not found."
#           exit 1
#         fi

#       # Deploy layer stack if needed
#       - |
#         if [ "$SKIP_LAYER_DEPLOY" != "true" ]; then
#           echo "=== Deploying LAYER stack ==="
#           sam build --use-container --template-file lambda1/template-layer.yaml
#           sam package \
#             --template-file .aws-sam/build/template.yaml \
#             --s3-bucket "$S3_BUCKET" \
#             --s3-prefix "lambda1/layer/$CODEBUILD_RESOLVED_SOURCE_VERSION" \
#             --output-template-file packaged-layer.yaml \
#             --region "$AWS_REGION"

#           sam deploy \
#             --template-file packaged-layer.yaml \
#             --stack-name "lambda1-layer-${ENVIRONMENT}" \
#             --parameter-overrides "Environment=$ENVIRONMENT" "LayerContentHash=$LAYER_HASH" \
#             --capabilities CAPABILITY_NAMED_IAM \
#             --region "$AWS_REGION" \
#             --no-fail-on-empty-changeset
#         else
#           echo "Skipping layer deploy (requirements unchanged)"
#         fi

#       # Ensure layer export exists (retry loop)
#       - |
#         echo "=== Waiting for LAYER export to appear ==="
#         for i in 1 2 3 4 5 6; do
#           LAYER_EXPORT="$(aws cloudformation list-exports \
#             --region "$AWS_REGION" \
#             --query "Exports[?Name=='lambda1-deps-layer-arn-${ENVIRONMENT}'].Name | [0]" \
#             --output text 2>/dev/null || echo "none")"
#           if [ "$LAYER_EXPORT" != "none" ] && [ "$LAYER_EXPORT" != "None" ]; then
#             echo "Layer export found."
#             break
#           fi
#           echo "Layer export not found yet (attempt $i) - sleeping 5s"
#           sleep 5
#         done
#         if [ "$LAYER_EXPORT" = "none" ] || [ "$LAYER_EXPORT" = "None" ]; then
#           echo "ERROR: Layer export still not found."
#           exit 1
#         fi

#       # Deploy function stack ALWAYS
#       - |
#         echo "=== Deploying FUNCTION stack ==="
#         sam build --use-container --template-file lambda1/template.yaml
#         sam package \
#         --template-file .aws-sam/build/template.yaml \
#         --s3-bucket "$S3_BUCKET" \
#         --s3-prefix "lambda1/function/$CODEBUILD_RESOLVED_SOURCE_VERSION" \
#         --output-template-file packaged.yaml \
#         --region "$AWS_REGION"

#         sam deploy \
#         --template-file packaged.yaml \
#         --stack-name "lambda1-${ENVIRONMENT}" \
#         --parameter-overrides "Environment=$ENVIRONMENT" \
#         --capabilities CAPABILITY_IAM \
#         --region "$AWS_REGION" \
#         --no-fail-on-empty-changeset

# artifacts:
#   files:
#     - packaged.yaml
#     - packaged-role.yaml
#     - packaged-layer.yaml

# cache:
#   paths:
#     - "/root/.cache/pip/**/*"
#     - ".aws-sam/**/*"


version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - set -euo pipefail
      - python --version
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - echo "ENVIRONMENT=$ENVIRONMENT"
      - echo "AWS_REGION=$AWS_REGION"
      - echo "S3_BUCKET=$S3_BUCKET"

  pre_build:
    commands:
      - set -euo pipefail

      # Hashes for change detection
      - LAYER_HASH=$(md5sum lambda1/layers/lib/requirements.txt | awk '{print $1}' | cut -c1-8)
      - ROLE_HASH=$(md5sum lambda1/template-role.yaml | awk '{print $1}' | cut -c1-8)

      # Decide role deploy needed (based on IAM role tag)
      - |
        ROLE_NAME="lambda1-execution-role-${ENVIRONMENT}"
        EXISTING_ROLE_HASH="$(aws iam get-role \
          --role-name "$ROLE_NAME" \
          --query "Role.Tags[?Key=='RoleHash'].Value | [0]" \
          --output text 2>/dev/null || echo "none")"

        if [ "$EXISTING_ROLE_HASH" = "$ROLE_HASH" ]; then
          SKIP_ROLE_DEPLOY=true
        else
          SKIP_ROLE_DEPLOY=false
        fi
        echo "SKIP_ROLE_DEPLOY=$SKIP_ROLE_DEPLOY"

      # Decide layer deploy needed (compare stack parameter)
      - |
        LAYER_STACK_NAME="lambda1-layer-${ENVIRONMENT}"
        STACK_EXISTS="$(aws cloudformation describe-stacks \
          --stack-name "$LAYER_STACK_NAME" \
          --region "$AWS_REGION" \
          --query "Stacks[0].StackId" \
          --output text 2>/dev/null || echo "none")"

        if [ "$STACK_EXISTS" != "none" ]; then
          EXISTING_LAYER_HASH="$(aws cloudformation describe-stacks \
            --stack-name "$LAYER_STACK_NAME" \
            --region "$AWS_REGION" \
            --query "Stacks[0].Parameters[?ParameterKey=='LayerContentHash'].ParameterValue | [0]" \
            --output text 2>/dev/null || echo "none")"
          if [ "$EXISTING_LAYER_HASH" = "$LAYER_HASH" ]; then
            SKIP_LAYER_DEPLOY=true
          else
            SKIP_LAYER_DEPLOY=false
          fi
        else
          SKIP_LAYER_DEPLOY=false
        fi
        echo "SKIP_LAYER_DEPLOY=$SKIP_LAYER_DEPLOY"

      # Bundle shared/ into lambda1/
      - rm -rf lambda1/shared
      - mkdir -p lambda1/shared
      - rsync -a --delete shared/ lambda1/shared/

      # Validate templates
      - sam validate -t lambda1/template.yaml
      - sam validate -t lambda1/template-role.yaml
      - sam validate -t lambda1/template-layer.yaml

  build:
    commands:
      - set -euo pipefail

      # -----------------------------
      # TemplateConfiguration JSONs (CORRECT SYNTAX for CodePipeline CFN action)
      # -----------------------------
      - |
        cat > role-config.json <<EOF
{
  "Parameters": {
    "Environment": "$ENVIRONMENT",
    "RoleHash": "$ROLE_HASH"
  }
}
EOF

      - |
        cat > layer-config.json <<EOF
{
  "Parameters": {
    "Environment": "$ENVIRONMENT",
    "LayerContentHash": "$LAYER_HASH"
  }
}
EOF

      - |
        cat > function-config.json <<EOF
{
  "Parameters": {
    "Environment": "$ENVIRONMENT"
  }
}
EOF

      # -----------------------------
      # ROLE template (conditional -> otherwise NO-OP template)
      # Output: lambda1-role.yaml
      # -----------------------------
      - |
        if [ "$SKIP_ROLE_DEPLOY" != "true" ]; then
          echo "=== BUILD/PACKAGE ROLE ==="
          sam build --use-container --template-file lambda1/template-role.yaml
          sam package \
            --template-file .aws-sam/build/template.yaml \
            --s3-bucket "$S3_BUCKET" \
            --s3-prefix "lambda1/role/$CODEBUILD_RESOLVED_SOURCE_VERSION" \
            --output-template-file lambda1-role.yaml \
            --region "$AWS_REGION"
        else
          echo "=== ROLE unchanged -> writing NO-OP lambda1-role.yaml ==="
          cat > lambda1-role.yaml <<'EOF'
AWSTemplateFormatVersion: '2010-09-09'
Description: 'No-op role deploy (skipped)'
Resources: {}
EOF
        fi

      # -----------------------------
      # LAYER template (conditional -> otherwise NO-OP template)
      # Output: lambda1-layer.yaml
      # -----------------------------
      - |
        if [ "$SKIP_LAYER_DEPLOY" != "true" ]; then
          echo "=== BUILD/PACKAGE LAYER ==="
          sam build --use-container --template-file lambda1/template-layer.yaml
          sam package \
            --template-file .aws-sam/build/template.yaml \
            --s3-bucket "$S3_BUCKET" \
            --s3-prefix "lambda1/layer/$CODEBUILD_RESOLVED_SOURCE_VERSION" \
            --output-template-file lambda1-layer.yaml \
            --region "$AWS_REGION"
        else
          echo "=== LAYER unchanged -> writing NO-OP lambda1-layer.yaml ==="
          cat > lambda1-layer.yaml <<'EOF'
AWSTemplateFormatVersion: '2010-09-09'
Description: 'No-op layer deploy (skipped)'
Resources: {}
EOF
        fi

      # -----------------------------
      # FUNCTION template ALWAYS
      # Output: lambda1-package.yaml
      # -----------------------------
      - |
        echo "=== BUILD/PACKAGE FUNCTION (ALWAYS) ==="
        sam build --use-container --template-file lambda1/template.yaml
        sam package \
          --template-file .aws-sam/build/template.yaml \
          --s3-bucket "$S3_BUCKET" \
          --s3-prefix "lambda1/function/$CODEBUILD_RESOLVED_SOURCE_VERSION" \
          --output-template-file lambda1-package.yaml \
          --region "$AWS_REGION"

artifacts:
  files:
    - lambda1-package.yaml
    - lambda1-role.yaml
    - lambda1-layer.yaml
    - role-config.json
    - layer-config.json
    - function-config.json

cache:
  paths:
    - "/root/.cache/pip/**/*"
    - ".aws-sam/**/*"
