version: 0.2

# Lambda1 Build Specification
# This buildspec builds ONLY Lambda1 function and the shared layer
# Lambda2 has a separate buildspec-lambda2.yml

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install AWS SAM CLI - packages Lambda functions for deployment
      - pip install --upgrade pip
      - pip install aws-sam-cli
      
      # Install CloudFormation linter - validates template syntax
      - pip install cfn-lint
      
      # Install Lambda1 dependencies
      # The -t flag puts dependencies in the same directory as app.py
      # This is required for Lambda to find the packages at runtime
      - cd lambda1 && pip install -r requirements.txt -t . && cd ..
      
      # Install shared layer dependencies
      # Layers have a specific structure: python/lib/python3.12/site-packages/
      # But SAM handles this automatically, we just need python/ directory
      - cd layers/shared && pip install -r requirements.txt -t python/ && cd ../..

  pre_build:
    commands:
      # Validate CloudFormation syntax before building
      - cfn-lint template.yaml
      
      # Placeholder for unit tests
      - echo "Running unit tests for lambda1..."

  build:
    commands:
      # SAM BUILD - Prepares Lambda code for deployment
      # --use-container: Builds in Docker to match Lambda runtime environment
      # --build-dir: Puts output in ./build directory instead of .aws-sam
      - sam build --use-container --build-dir ./build
      
      # SAM PACKAGE - Creates deployment-ready package
      # Takes the built code and uploads it to S3
      # Generates packaged.yaml with S3 URLs instead of local paths
      # CloudFormation will download from S3 during deployment
      - sam package
        --template-file build/template.yaml
        --s3-bucket $ARTIFACT_BUCKET
        --s3-prefix lambda1/$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        --output-template-file packaged.yaml
        --region $AWS_REGION

  post_build:
    commands:
      - echo "Lambda1 build completed successfully"

artifacts:
  files:
    - packaged.yaml
  name: Lambda1BuildArtifact

# Cache pip packages to speed up subsequent builds
cache:
  paths:
    - '/root/.cache/pip/**/*'

env:
  variables:
    AWS_REGION: us-east-1
    ARTIFACT_BUCKET: lambda-monorepo-lambda1-artifacts
