AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles for Lambda Monorepo CodePipeline

Resources:
  # CodePipeline Service Role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-monorepo-codepipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::lambda-monorepo-artifacts'
                  - !Sub 'arn:aws:s3:::lambda-monorepo-artifacts/*'
              - Sid: CodeBuildAccess
                Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:BatchGetReports
                  - codebuild:CreateReport
                  - codebuild:CreateReportGroup
                  - codebuild:UpdateReport
                  - codebuild:UpdateReportGroup
                Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/lambda-monorepo-*'
              - Sid: CodeBuildBatchAccess
                Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/lambda-monorepo-*'
              - Sid: CloudFormationAccess
                Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStackResources
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ListChangeSets
                Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/lambda-monorepo-*'
              - Sid: PassRole
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt CloudFormationServiceRole.Arn

  # CodeBuild Service Role
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-monorepo-codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/lambda-monorepo-*'
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::lambda-monorepo-artifacts'
                  - !Sub 'arn:aws:s3:::lambda-monorepo-artifacts/*'
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  # CloudFormation Service Role
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-monorepo-cloudformation-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: CloudFormationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LambdaPermissions
                Effect: Allow
                Action:
                  - lambda:*
                  - apigateway:*
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - cloudwatch:*
                  - logs:*
                  - iam:*
                Resource: '*'

Outputs:
  CodePipelineRoleArn:
    Description: ARN of the CodePipeline IAM Role
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: lambda-monorepo-codepipeline-role-arn

  CodeBuildRoleArn:
    Description: ARN of the CodeBuild IAM Role
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: lambda-monorepo-codebuild-role-arn

  CloudFormationRoleArn:
    Description: ARN of the CloudFormation IAM Role
    Value: !GetAtt CloudFormationServiceRole.Arn
    Export:
      Name: lambda-monorepo-cloudformation-role-arn
